language: node_js
os: linux
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run build
  - npm test
  - npm run coverage
